### PR TITLE
Add discussion of media type registration

### PR DESCRIPTION
**Pull request by djc**
Unfortunately I won't be able to attend -- I hope someone else can take the lead in the discussion, but it seems pretty straightforward.

### CODE REVIEW

**Comment by binji** [comment]
Sorry, I didn't notice this until now. Let's bump this discussion to the next meeting (July 21st).

**Comment by djc** [comment]
I think @ericprud will take this forward at the next meeting.

**Comment by ericprud** [comment]
Actually, I'll be on a bike trip on the 21st, but if no one objects at the meeting, I can grab some bits somewhere to press the buttons.

**Comment by dtig** [comment]
Thanks to @ericprud, [application/wasm](https://www.iana.org/assignments/media-types/application/wasm) has been registered. Closing this issue.

**Pull request closed without merging**
