### PR TITLE
Add poll about WebAssembly.Global default value

### PR DESCRIPTION
**Pull request by binji**

### CODE REVIEW

**Comment by binji** [comment]
This should be a quick topic, added it to Wednesday since it seemed like a lighter day, but we can probably squeeze it in anywhere.

**Comment by binji** [comment]
@jfbastien I fixed the conflict, does this seem like an OK time or should we move it?

**Comment by jfbastien** [comment]
You mean `+0.0` 😄

**Comment by jfbastien** [comment]
I'll reshuffle the schedule as we get closer to the date.

**Pull request merged**
