### PR TITLE
Update on Branch Hinting proposal

### PR DESCRIPTION
**Pull request by yuri91**
Hi! I would like to do a brief update about my work on the branch hinting proposal in the next meeting.

### CODE REVIEW

**Comment by dtig** [comment]
@yuri91 If this is not a time sensitive update, would you be okay presenting at the 01/19 meeting instead? The meeting is tomorrow, and we don't have other agenda items right now.

**Comment by yuri91** [comment]
Honestly I was hoping to make some progress on the proposal by gathering some feedback on the new approach. The last meeting was more than a month ago...

**Comment by RossTate** [comment]
If there's a meeting tomorrow, I was about to suggest we discuss activating the new GitHub Discussions feature for the various repos.

**Comment by dtig** [comment]
Sure, sounds good. The intent of moving this was to avoid convening a large group for short meetings. Will keep the agenda as-is as the last meeting was cancelled as well.

**Comment by yuri91** [comment]
thanks!

**Pull request merged**
