### PR TITLE
Add announcement for Oct 23 SOIL Seminar

### PR DESCRIPTION
**Pull request by RossTate**

### CODE REVIEW

**Review by tlively — APPROVED** [review]
👍

**Comment by sbc100** [comment]
Was there a recording made of today's one?   (Obviously it only just happened so maybe a delay but I'd love to see it if/when its available).

**Comment by penzn** [comment]
I'd love to see that too - went to add the meeting to calendar only to find out I was an hour late :(

**Comment by RossTate** [comment]
The recording can be found here: http://soil-initiative.org/seminar/#20201012

**Pull request merged**
