### PR TITLE
Update WG-12-14.md

### PR DESCRIPTION
**Pull request by rossberg**

### CODE REVIEW

**Review by pchickey — APPROVED** [review]

**Comment by rossberg** [comment]
Yes, I think this won't make much sense without @ericprud, since he apparently is the only one who understands and controls the process. :)

Happy to push it to the next date if too many people can't make it. That would be the Jan 11th?

**Comment by dschuff** [comment]
Yes, January 11. That date would also work for me, let's see what some other folks say about their availability (I also forgot to @lukewagner in my last post)

**Comment by dtig** [comment]
I'll be around for the 14th, but agree with @rossberg that we probably want @ericprud around for the discussion. I'm sometimes unable to participate actively during that time slot, and only have one question re. Wasm 2.0 so I'll just post here. We had previously decided that a CR should go out for every major version bump, is a CR needed for the 2.0 bump? It doesn't look like the [previous CR](https://github.com/w3c/transitions/issues/119) covers the recent changes before the major version change.

**Comment by ericprud** [comment]
The last published version was on [19 April 2022](https://www.w3.org/TR/2022/WD-wasm-core-2-20220419/). The evergreen approach allows for arbitrary (capricious) publication of CRs;  I believe we said we'd do it whenever a proposal was merged (I don't see any in [Finished Proposals](https://github.com/WebAssembly/proposals/blob/main/finished-proposals.md)) so we might want to gear up for more frequent publication.

**Comment by rossberg** [comment]
Actually, it turns out that I myself cannot make it next Wednesday. :-} So let's perhaps push to January.

**Comment by dschuff** [comment]
ok, I'll cancel tomorrow. @ericprud can you let us know how to find out our W3C rep's availability for January?

**Comment by ericprud** [comment]
I just got word that @plehegar will be taking over for me. It would probably make sense for both of us to attend the 11 Jan meeting. Plh, would that work for you?

**Comment by plehegar** [comment]
Yes, I'll be there

**Comment by dschuff** [comment]
I've updated the agenda for Jan 11 in #1192

**Pull request closed without merging**
