### PR TITLE
Update CG-08-13.md

### PR DESCRIPTION
**Pull request by tlively**

### CODE REVIEW

**Comment by tlively** [comment]
cc @guybedford and @alexcrichton for slides links

**Comment by guybedford** [comment]
Slides available at https://docs.google.com/presentation/d/1Po0FlImrq1DJUARuZRssDshVtQGwz-YlnsdVrkA2UvE.

**Comment by alexcrichton** [comment]
Mine are at https://docs.google.com/presentation/d/1szj9D2q43NrQhxtys2OBAAMjeAOanCNMIS4D0gPaYuI

**Comment by alexcrichton** [comment]
@tlively or @dschuff would y'all be able to set up a new proposal repo and give @jameysharp and I access?

**Comment by tlively** [comment]
Yep, I can take a stab at that.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
