### PR TITLE
Add poll for BigInt<->i64 advancement

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by Ms2ger** [comment]
I added this before the discussion point because it should not take an open-ended amount of time.

CC @xtuc

**Comment by Ms2ger** [comment]
Sorry, didn't see #553 before.

**Comment by xtuc** [comment]
I agree with @Ms2ger that the discussion should take too long.

**Comment by dtig** [comment]
No issues, will merge this one and delete the other.

**Pull request merged**
