### PR TITLE
Add K presentation to CG-04-16

### PR DESCRIPTION
**Pull request by binji**

### CODE REVIEW

**Comment by binji** [comment]
@chicoxyzzy do you mind if we do this presentation first? It will likely take a fixed amount of time, and the discussion around inclusiveness will vary.

**Comment by chicoxyzzy** [comment]
@binji sure, I think it's better to make discussion about inclusion to the end of agenda

**Comment by grosu** [comment]
How much time do we have for the presentation on K?  @ehildenb will most likely give our presentation, who is also working on the WASM semantics in K: https://github.com/kframework/wasm-semantics.  He will talk about both K and the current status of WASM in K.  Hope this is OK.

**Comment by binji** [comment]
> How much time do we have for the presentation on K?

The meeting is an hour long, and we have a discussion afterward. I think 20-30 minutes would probably be OK.

> Hope this is OK.

Yes, sounds good!

**Pull request merged**
