### PR TITLE
Add charter discussion item to WG-09-13.md

### PR DESCRIPTION
**Pull request by lukewagner**

### CODE REVIEW

**Comment by dschuff** [comment]
LGTM, assuming @sideshowbarker can make it

**Review by dschuff — APPROVED** [review]

**Comment by justinmichaud** [comment]
Can we have this discussion when folks who are attending TPAC can attend?

**Comment by dschuff** [comment]
Ah yes; indeed we should if there's interest (and also I expect that @sideshowbarker will be at TPAC too). Maybe it makes more sense to delay the meeting by a week than to try to work around TPAC.
Or, the next regularly-scheduled WG meeting is actually the day of the in-person CG meeting. So another option could be to schedule some time there that all the interested people can make.

**Comment by sideshowbarker** [comment]
I will be at TPAC and the 8:00 AM PDT slot works out to 5:00 PM CET — and on the “breakout sessions” day — so it seems like it _should_ be possible for any Web Assembly WG members at TPAC to attend the call. At least for me part, I could. But if it seems better to delay the WG meeting for this until after TPAC, that’s also fine by me.

**Comment by dschuff** [comment]
Sorry I dropped the ball on this. With apologies for the late notice, I think it's probably better to punt it to next week. I'll move the calendar event and update the repo.

**Pull request merged**
