### PR TITLE
Add discussion of NSF Expedition to CG-08-06

### PR DESCRIPTION
**Pull request by RossTate**

### CODE REVIEW

**Comment by binji** [comment]
@RossTate how long do you expect this discussion/presentation to be? At a previous meeting we discussed canceling meetings that were not going to have at least 30 min of topics.

@dtig @dschuff FYI

**Comment by RossTate** [comment]
@binji This is somewhat time sensitive. I am looking to try to get $10 million dollars from the US government for WebAssembly to bring a multi-university team of researchers on board the project, but it's a ton of work so before we get started we want to get some sort of approval from the CG so that our efforts aren't for nothing. Right now is the best time to get started since none of us are teaching classes over summer, and we're already late to get started on this, so even delaying two weeks would let a critical window slip by. How long the discussion takes completely depends on the number of questions and suggestions the CG has for us.

**Comment by RossTate** [comment]
I also normally can’t make Tuesdays—this week is a fortuitous exception I’m trying to take advantage of.

**Comment by dtig** [comment]
Merging as this is time sensitive.

**Comment by RossTate** [comment]
Thanks!

**Pull request merged**
