### PR TITLE
Add GC subgroup notes for 12/15

### PR DESCRIPTION
**Pull request by tlively**
@RossTate, thanks for presenting! Can you open a PR against this branch to add your slides?

### CODE REVIEW

**Comment by RossTate** [comment]
Done! #688

**Comment by tlively** [comment]
I'll leave this open for a week or so in case anyone else has changes they want to make.

**Comment by taralx** [comment]
List of names needs bullet points or spaces at EOL.

**Comment by tlively** [comment]
Thanks for catching that, @taralx. I've also updated the Google doc for the notes so I will remember to bullet the names in the future as well.

**Pull request merged**
