### PR TITLE
Discuss: It's hard to contribute on proposals.

### PR DESCRIPTION
**Pull request by cardil**
I find it difficult to contribute to existing proposals. They are a forked WASI repos with additional files.

There's no space for discussion on them, other than creating a PR that targets the fork. I'd like to have a space to discuss first (Github discussions, maybe?!?). Even, opening an PR is hard as it may interfere with the main maintainer commits.

I think the better might be to commit (by PR) a stub of a proposal first. So, then multiple people could provide parts of the proposal in smaller chunks.

### CODE REVIEW

**Comment by sbc100** [comment]
I think the idea (as with WebAssembly proposals) is that one can open issues and PR in the forked repository, keeping the discussion local to the proposal.   We tend to use github issues for "discussions" but maybe we can move to the official github discussions thing instead?  I'm not sure it make that much difference.  Happy to discuss further in the meeting of course.

**Comment by linclark** [comment]
Heads up, this process is on the verge of changing already.

This has been discussed in multiple WASI meetings, and in the issue queue with https://github.com/WebAssembly/WASI/pull/451 (which I am planning to merge today).

**Comment by sbc100** [comment]
> Not all forks have issues enabled. I'm interested the most in https://github.com/badeend/WASI-Networking, but I saw a couple of other ones, do not have issues enabled as well.

That sounds like a bug with those proposals.. for sure proposal should have issues enabled.

**Comment by linclark** [comment]
Totally agreed—all proposals in the Proposals list should have issues enabled. Thanks for raising that. I'll go through that list and contact the champions wherever that's not the case right now.

I merged https://github.com/WebAssembly/WASI/pull/451, and with that, we won't be using forks anymore but instead will use this [proposal template](https://github.com/WebAssembly/wasi-proposal-template).

@cardil Why don't you take a look at the updated WASI repo and the proposal template and see whether you still think there are still issues to be discussed in the meeting. If you do still think it needs a synchronous discussion after that, just ping here before next Wednesday and I'll merge this PR.

**Comment by cardil** [comment]
I'll take a look. Converting to draft for now.

**Pull request closed without merging**
