### PR TITLE
Update CG-06.md

### PR DESCRIPTION
**Pull request by camio**
Add discussion on dealing with large WASM binaries

### CODE REVIEW

**Comment by tlively** [comment]
Thanks for the suggestion! A few questions for planning purposes: What kind of discussion are you planning for? Do you plan to present? How much time do you have in mind?

**Comment by camio** [comment]
I could deliver a short presentation outlining the general problem, the solutions we have, and the gaps. My hope is that it would turn into a bit of a brainstorming session. I was thinking 30m-1h.

**Comment by tlively** [comment]
Thanks, that sounds good. We plan to set a concrete agenda on Tuesday, so hopefully we can fit this in. Can you fix the conflict? Then I'll merge this.

**Comment by camio** [comment]
@tlively Done!

**Pull request merged**
