### PR TITLE
Update CG-05.md

### PR DESCRIPTION
**Pull request by dtig**
Update the agenda to include new SIMD items.

### CODE REVIEW

**Comment by jfbastien** [comment]
Should we only talk about horizontal addition, or should we talk about horizontal operations in general? And which types are we talking about?

I'd like to have more details here, including which ISAs support what operations.

**Comment by dtig** [comment]
I've added more details from the tracking issue. We should talk about horizontal addition, as horizontal operations in general do not have consistent ISA support. 

SSE3/ARMv8 natively support horizontal addition for f32x4, i32x4, and i16x8, @stoklund proposed including f64x2 as well. Horizontal adds for i8x16 are not natively supported on the x86 ISA, but can be implemented using PSADBW.

**Comment by jfbastien** [comment]
But why just add though?

**Comment by dtig** [comment]
We've had some feedback that these would be useful to have for performance with complex multiplications, other operations do not have consistent ISA support (Ex. Horizontal subtracts on ARM). I can edit the agenda item to discuss horizontal operations in general if you think that would be more useful.

**Comment by jfbastien** [comment]
What I meant was: the poll only mentions add, and it isn't clear why just this one. Having the extra context would be useful, otherwise we'll discuss the poll itself.

Separately, it may be worth having another poll which asks: do we want horizontal operations for other instructions? The presumption you have is that the answer is "no". That's fine! Polling for a "no" vote is a good way to ensure what you believe is what the committee also believes. Maybe just raising the poll will bring in new information which will change your opinion. Maybe people will offer guidance on what would convince them to say "yes" later (e.g. ISA support, perf numbers, specific usecases, etc).

**Comment by dtig** [comment]
I see what you mean, thanks for clarifying! I've updated the pull request.

**Pull request merged**
