### PR TITLE
Propose agenda for SIMD meeting 2024-07-19

### PR DESCRIPTION
**Pull request by ppenzin**
https://github.com/WebAssembly/flexible-vectors/issues/64

### CODE REVIEW

**Comment by dtig** [comment]
@ppenzin would it be ok to move it forward by 1-2 weeks? Some folks will be traveling back from the hybrid CG meeting at the time this meeting is scheduled. Generally supportive of figuring out how to expose horizontal operations though.

**Comment by ppenzin** [comment]
Yeah, I think that would be fine, also a bit of a late notice for the people involved in the LLVM change.

**Comment by sparker-arm** [comment]
If horizontal operations are on the table, I wouldn't mind attending to hear other people's thoughts. I will be on holiday until the week commencing 24th though.

**Comment by ppenzin** [comment]
@dtig @sparker-arm I'll bump the by two weeks for now, and can push this item one more time.

**Comment by ppenzin** [comment]
"Bump by two weeks" ends up being right after July 4th in the US, which I expect a lot of people have off or take off. Let's move that one more time.

@sparker-arm Anton has mentioned you've built TSVC for Wasm, will be curious to hear about that, I've been working on it a bit lately, though mostly in a different context.

**Comment by ppenzin** [comment]
Planning for July 19th, though the slot on the 12th might be available if there is nothing on benchmarking meeting agenda.

**Comment by sparker-arm** [comment]
> Anton has mentioned you've built TSVC for Wasm

@ppenzin I've actually been using an updated version: [TSVC 2](https://github.com/UoB-HPC/TSVC_2) which compiles and runs, in wasi environment, with no trouble.

**Comment by ppenzin** [comment]
@sparker-arm can you share your makefile for Emscripten? I've been using TSVC 2 as well, had to update (native) Clang flags and fix std library calls on non-Linux platforms. I have a [public fork](https://github.com/tenstorrent/TSVC_2) of the repo with all that and individual test builds.

**Comment by ppenzin** [comment]
This been up for a while and there seems to be consensus about time and agenda, I am going to just merge this.

**Comment by sparker-arm** [comment]
> can you share your makefile for Emscripten? I've been using TSVC 2 as well, had to update (native) Clang flags and fix std library calls on non-Linux platforms.

Ah, sorry, I'm targeting WASI :)

**Comment by ppenzin** [comment]
WASI is fine too. I can probably poke around to get the JS-adjacent version running as well.

**Comment by sparker-arm** [comment]
Well, there's nothing to share really... But I have remembered that I did make one notable source change, in common.c, and that was replacing `memalign` calls with `aligned_alloc`.

**Pull request merged**
