### PR TITLE
Add some agenda items

### PR DESCRIPTION
**Pull request by rossberg**

### CODE REVIEW

**Comment by conrad-watt** [comment]
Are @fgmccabe, @slindley and @dhil ok with these scheduling restrictions (I assume this is to facilitate remote participation from Edinburgh)?

For reference (and @fgmccabe please chime in here), are fibers and typed stack switching in some way mutually exclusive or could we imagine both being ultimately standardised?

**Comment by rossberg** [comment]
@conrad-watt, yes, @dhil will be on site, but @slindley can't come. I took the liberty to assume that @fgmccabe won't mind either way, but let us know if that's a problem.

The proposals are either mutually exclusive or we find a way to converge them. Personally, I doubt we'll be in a suitable state for voting.

**Comment by tlively** [comment]
GC phase 3 poll at the meeting SGTM!

**Comment by fgmccabe** [comment]
yes

**Pull request merged**
