### PR TITLE
Defer GC subgroup topic

### PR DESCRIPTION
**Pull request by rossberg**
Unfortunately, I can't attend tomorrow due to a family incident, so I'm pushing the item to the next meeting.

### CODE REVIEW

**Comment by RossTate** [comment]
Given that this is purely organizational and was already deferred from the in-person meeting, could someone like @lukewagner not take this discussion over so that we can get the momentum building?

**Comment by binji** [comment]
I agree that this is mostly organizational. Do we need to have any discussion more than agreeing to create the subgroup?

**Comment by dtig** [comment]
Perhaps we should discuss this offline instead of at a meeting? I suspect the forming of the subgroup itself is non-contentious, but there may be open items to discuss regarding the details of the charter. Are there any objections to cancelling this meeting and discussing the details in an issue? That way we can possibly make progress without waiting the additional two weeks, and @rossberg can also chime in asynchronously when possible.

**Comment by RossTate** [comment]
Hmm, I guess the question is how do we determine who wants to be involved, either in the subgroup or in hashing out whatever details need to be resolved to form a subgroup? (I do not know the subgroup process, so I have no idea what those details are.)

**Comment by binji** [comment]
Generally anyone who wants to be involved can be. There is no official subgroup process, but the way we've done it in the past is to have a charter, and separate meetings for that group. In essence it's primarily a way to have more focused discussions.

**Comment by RossTate** [comment]
Sounds good. I realized I should have said earlier that I have no objection; I am just wondering as a newcomer how we invite people to get involved.

**Comment by binji** [comment]
> I am just wondering as a newcomer how we invite people to get involved.

All they have to do is [join the CG](https://www.w3.org/community/webassembly/), then they can be involved. With other subgroups we've had regular (usually every two weeks) meetings, I'd suggest we do the same here. See, for example, the [interface types meetings](https://github.com/WebAssembly/interface-types/issues/81) or [simd meetings](https://github.com/WebAssembly/simd/issues/202).

**Comment by binji** [comment]
I've [created an issue here](https://github.com/WebAssembly/gc/issues/80) to discuss. In the meantime, let's cancel tomorrow's meeting.

**Comment by dtig** [comment]
Thanks Ben, leaving a link here to the [debugging subgroup meetings](https://github.com/WebAssembly/debugging/tree/master/meetings) as well. Meeting tomorrow is now cancelled.

**Comment by RossTate** [comment]
Thanks for all the links and filing the issue to get things going! I'll get reading to catch up :)

**Pull request merged**
