### PR TITLE
Add notes for 2021-06-08

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
@KloudKoder @yuri91 can you post links to your presentations?

**Comment by KloudKoder** [comment]
@dschuff Hmm... I don't know where to upload mine. Should I just attach it somewhere on Github.

**Comment by yuri91** [comment]
here you go: https://drive.google.com/file/d/1NYFMqDtikAr7ClLK-4XUPQme_ftDZb3T/view?usp=sharing

**Comment by dtig** [comment]
Thanks @yuri91. 

@KloudKoder, you can upload your presentation to the presentation to the [presentations directory](https://github.com/WebAssembly/meetings/tree/main/main/2021/presentations), or provide a public link.

**Comment by KloudKoder** [comment]
@dtig Hmm it says "File uploads require push access to this repository."

**Comment by dcodeIO** [comment]
Instead of pushing directly, you could fork this branch, apply and commit the changes to your fork, and create a pull request from your branch to this branch. Then someone can merge it :)

**Comment by KloudKoder** [comment]
@dcodeIO I'll wait for a reply from dtig. Github drives me nuts and I don't want to make a mess of everything. Nevertheless I appreciate your suggested workaround, which might be necessary.

**Comment by fgmccabe** [comment]
github drives me nuts too :) The workflow that Daniel suggested is standard but only obvious to a died in the wool GitHubber.

**Comment by dtig** [comment]
@dcodeIO's suggested workflow works, if you would find submitting a PR to the main repo easier, I'm happy to merge it in and link it into the notes as well.

**Comment by KloudKoder** [comment]
@ditg I tried to fork the repo, but when I did that, the June 8 meeting disappeared. So I gave up and submitted a PR to the main repo as you suggested. But then the "Issue" dropdown disappeared, so I couldn't send you a link back to the issue I posted. I hate using GitHub because it creates a complexity explosion out of thin air every time, but obviously we're stuck with that.

**Comment by dschuff** [comment]
I'll go ahead and merge this. Then any fork can be up-to-date and PRs can be against this. You can give it another try, or if you want you can just send it to me at dschuff @ chromium.org and I'll post it.

**Pull request merged**
