### PR TITLE
Update CG-09-17.md

### PR DESCRIPTION
**Pull request by eqrion**

### CODE REVIEW

**Comment by dtig** [comment]
@eqrion Thanks for your PR, please join the [WebAssembly CG](https://www.w3.org/community/webassembly/#) to attend, and present at the meeting. 

It's only a few hours to this meeting, and we try to make sure to not include agenda items less than a day before the meeting to be inclusive of timezones so folks can plan to attend. If this is not time sensitive, please submit a PR to the next meeting two weeks from now instead of this one after joining the CG.

**Comment by eqrion** [comment]
@dtig Oh, I wasn't aware that CG membership was required to attend. I've attended a couple previous meetings already and assumed W3C membership was good enough. I just submitted an application to join the CG.

This isn't exactly time sensitive, however it would be convenient to not wait two weeks to discuss this issue. However, I understand and I'm fine either way.

**Comment by dtig** [comment]
@eqrion The [registration](https://github.com/WebAssembly/meetings/blob/master/2019/CG-09-17.md#registration) section in the agenda has the bit that talks about CG participation. Generally attendees are asked to join the CG, but sometimes exceptions can be made for observers. In this case as you will be contributing, I would suggest joining the CG first.

**Comment by eqrion** [comment]
I will open a PR for the next CG meeting.

**Pull request closed without merging**
