### PR TITLE
Add some info on the June in-person CG meeting

### PR DESCRIPTION
**Pull request by binji**

### CODE REVIEW

**Comment by binji** [comment]
@littledan is there more info we can add here? (accidentally pushed previously as a commit)

**Comment by littledan** [comment]
We were planning on having the meeting at our headquarters:

Bugallal Marchesi, 22, 1º
15008 A Coruña
Galicia (Spain)
Tel.: +34 981 913991

For time, whatever's preferable for the group; we are flexible.

**Comment by binji** [comment]
@littledan Can you add some info about nearby hotels, how best to travel to A Coruña? We've had some folks find that booking the madrid-A Coruña flight separately saved some money.

**Comment by littledan** [comment]
@binji I didn't realize people were booking the travel so far in advance; I've asked others in Igalia if they can post travel advice soon.

**Pull request merged**
