### PR TITLE
Preproposal phase update

### PR DESCRIPTION
**Pull request by arunetm**
Updating pre-proposal phase description to recommend issue creation in the proposal repo instead of design repo.

### CODE REVIEW

**Comment by aretmr** [comment]
@binji please review the accuracy of this update to the description of phases.

**Comment by binji** [comment]
Seems like a good idea. One reason folks liked having a separate proposals repo is that it would be less noisy than following the design repo, and this could change that. But we haven't seen a huge number of new proposals, so it's probably OK.

**Comment by chicoxyzzy** [comment]
IMO it's better to keep new pre-proposals in design repo.

**Comment by dtig** [comment]
As it's been some time, and we've continued to use the design repo for new proposals I'm closing this PR - please feel free to reopen/follow up if necessary.

**Pull request closed without merging**
