### PR TITLE
Create CG-12-08.md

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
Sorry I didn't get this file created sooner.

There haven't been any public or private requests for agenda items for tomorrow; historically we've tried to get them 24h in advance and cancelled meetings for lack of agenda, but we haven't been super-consistent about it. Maybe we should leave it open until this evening Pacific (or maybe mid-morning CET) to give folks a chance for tomorrow.

**Comment by RossTate** [comment]
One (light?) discussion item that came up in the GC subgroup but does not seem GC specific is computational complexity of validation. That is, do we want validation to be decidable, and if so do we want any complexity bounds on it? I feel like it would help us to have some at least informal consensus on the topic, and in today's seminar I got the impression that it would help researchers exploring WebAssembly extensions/analyses/optimizations have a sense of what kinds of systems would be practical. Dunno if such a discussion merits a whole CG meeting, or if it would be better done over a (Design?) issue, but I figured I'd mention the idea here to gauge interest.

**Comment by aheejin** [comment]
One thing to note is that this overlaps with Google's internal org meeting that happens to contain many people working on wasm, so the attendance can be lower than usual.

**Comment by RossTate** [comment]
Ah, thanks for the info @aheejin. It would be kind of pointless to have a discussion like the one I suggested above with a bunch of people missing.

**Comment by dschuff** [comment]
Yeah, it's probably not worth keeping the meeting just for that. Given that we still haven't gotten topics, I'll cancel this one and try to be better with getting the agenda boilerplate posted earlier next time.

**Comment by dschuff** [comment]
will cancel for lack of agenda

**Pull request closed without merging**
