### PR TITLE
Discussion of IT strings in CG-08-03

### PR DESCRIPTION
**Pull request by dschuff**
This is sort of what I had imagined the structure might be; i.e. have @lukewagner's presentation, as well as an opportunity for @dcodeIO to make a case for UTF-16 lifting/lowering (and presumably against USV semantics at IT boundaries?), followed by 2 votes. 
But I'm open to ideas about how best to structure this. Maybe it makes sense to timebox presentations or discussions separately? One thing I guess I had assumed but don't actually know: @dcodeIO do you plan to make a presentation, or do you just want to go right into discussion on one particular issue or the other? @lukewagner I assume you have a presentation planned, do you have an estimate for how long it would be?

### CODE REVIEW

**Comment by dcodeIO** [comment]
I wasn't planning to give a presentation as I am feeling really sick right now. I will probably be unable to participate much given the harassment I have endured and are still subjected to, yet I think that my written concerns are critical to help the group make an informed decision on the second poll.

**Comment by dcodeIO** [comment]
There is also a [concrete suggestion for a solution](https://github.com/WebAssembly/interface-types/issues/135#issuecomment-889502869) that could be linked / talked about.

**Comment by dtig** [comment]
> I wasn't planning to give a presentation as I am feeling really sick right now. I will probably be unable to participate much given the harassment I have endured and are still subjected to, yet I think that my written concerns are critical to help the group make an informed decision on the second poll.

I'm still catching up on the various threads, but I'd like to leave a quick note here that characterizing technical disagreement as harassment is triggering, and harmful to leave unchecked. I've taken time to review posts on issues, and reached out to you in good faith when these claims were made previously, and have not had anything actionable to follow up on. This is a very serious accusation and not to be thrown around lightly - so reach out to the chairs if you have encountered behavior violating the [W3C CEPC](https://www.w3.org/Consortium/cepc/).

**Comment by dcodeIO** [comment]
Suggesting that I'd be throwing this around lightly after all that has been done to me for almost four years over what should be allowed technical arguments, now even affecting my physical health, is irritating at best. I have complained a couple times but eventually gave up because I had to realize that nothing ever changes anyhow, and that if someone is penalized then it's me. I do not even understand anymore why the CEPC exists, as its words and spirit are regularly violated when it's only me who is harmed.

**Comment by dtig** [comment]
To be clear, your complaints were around technical arguments, as you say so yourself, that is very different from making repeated, unsubstantiated claims of harassment. 

One of the goals of the CEPC is to "Ensure an environment where people can participate without fear of harassment.". I've asked for links to evidence, or documented cases to back your claims of harassment or CEPC violations, as there is no evidence of that in the publicly available GitHub discussions but that has not materialized thus far.

**Comment by dcodeIO** [comment]
I have a multi-page document, but I also figured that if it's not obvious by now then an entire technical body is just failing, and sending it would not lead to anything good anyhow. I want us all to cooperate and to feel well about it even if there is technical disagreement, and the first step would be to acknowledge that there is an issue so we can talk about this constructively and resolve it, instead of me sending half a book of complaints to the ombuds.

**Comment by dtig** [comment]
I think we can all agree that there is a technical disagreement, and I see several folks engaging with you constructively. But if you are making claims of being harassed, or being targeted by CEPC violations publicly, the responsibility of the chairs is to follow up with you - but so far you haven't found evidence to offer on further consideration any of the times we've followed up with you.

**Comment by dcodeIO** [comment]
Right, even the person who openly insulted me a while back, with members of the WG upvoting instead of stepping in, is here again, upvoting others and commenting.

**Comment by dtig** [comment]
Before this escalates into something more unproductive, I'll summarize and give you concrete next steps that you can follow up on if you like.

- Please follow up with the chairs if you have been the target of CEPC violations, and/or harassment through the appropriate channels, and with specifics if you would like anything actionable to be done. If not, refrain from making unsubstantiated claims
- As you've mentioned before that you are of the opinion that the technical body is failing, or not enough has been done to address your complaints, as a W3C member, I wanted to make you aware of your options for escalation that are documented [here](https://www.w3.org/Consortium/pwe/#ombuds).

I don't have more to say on this issue, so I'll hand off to @dschuff so as to to not derail this PR, which is making sure we have a well formed agenda for the meeting next week.

**Comment by dschuff** [comment]
(pasting the description from commit e418ba6 here, since Github is hiding it)

I added @dcodeIO's suggestion as an additional link (hopefully most folks will have read 135 anyway), and removed the item nesting (I think that conceptually makes more sense) and the individual timeboxing.
I also changed "summary" to "discussion" since there won't be a formal presentation; I will make sure to bring up the concerns specifically, but I don't think I will try to summarize them (presentation-style) myself, since I don't want to misrepresent anyone or really advocate any positions. Hopefully some participants can elaborate or say what their most important concerns are.

**Comment by dschuff** [comment]
I'll merge this since I think it's an improvement, agendawise. Comments or further PRs are welcome.

**Pull request merged**
