### PR TITLE
Add agenda item for interval primitives

### PR DESCRIPTION
**Pull request by KloudKoder**
I'll have a more formal draft document, but the idea is here:

https://github.com/WebAssembly/design/issues/1384

### CODE REVIEW

**Comment by dtig** [comment]
Thanks, could you comment, or update the PR with the amount of time you expect this agenda item to take?

**Comment by KloudKoder** [comment]
@dtig @penzn I can probably get the basics across and have some question time in 40 minutes. Does that work?

**Comment by dtig** [comment]
There are no other agenda items right now, so that should work.

**Comment by KloudKoder** [comment]
Hi, I'm supposed to present in 10 minutes but I just realized that I never received this "calendar invite" for the Zoom link. I'm not sure which calendar it's referring to. Responding to this thread so hopefully it won't go into your spam.

Please inform.

Thanks,
Kloud Koder

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
