### PR TITLE
Add vectors co-champion announcement to CG-09-26.md

### PR DESCRIPTION
**Pull request by penzn**

### CODE REVIEW

**Comment by penzn** [comment]
I am putting this as the first item, because I don't think there would be any discussion, just a consent vote if I'm not mistaken.

**Comment by dtig** [comment]
No vote needed, an announcement or a PR to the proposals repository should work.

**Comment by penzn** [comment]
Perfect, made it an announcement, will work on the PR as well

**Comment by penzn** [comment]
https://github.com/WebAssembly/proposals/pull/173, I can't add reviewers there.

**Review by dschuff — APPROVED** [review]

**Pull request merged**
