### PR TITLE
Add two-phase unwinding discussion part 2

### PR DESCRIPTION
**Pull request by aheejin**
In the last meeting we only covered the problem part, so I'd like to
present and discuss our proposed changes.

### CODE REVIEW

**Comment by binji** [comment]
Sounds good, I just want to make sure we give time for discussion in this session.

**Comment by aheejin** [comment]
Still not sure 25 mins is enough for remaining presentation + discussion + poll, but I was also not sure if it was OK to hog the whole meeting like 45 mins for my agenda alone..

**Comment by binji** [comment]
We already have https://github.com/WebAssembly/meetings/pull/626 too. So we should try to make 25-30 min work here, if we can. I wouldn't want it to extend out to another two weeks.

**Comment by aheejin** [comment]
Increased it by 5 mins in #628.

**Pull request merged**
