### PR TITLE
Add an agenda item for non-trapping float-to-int conversions.

### PR DESCRIPTION
**Pull request by sunfishcode**
The [nontrapping float-to-int conversion proposal](https://github.com/WebAssembly/nontrapping-float-to-int-conversions) now has spec text, an interpreter implementation, and testsuite coverage. There are presently no outstanding issues or PRs, and no other known outstanding concerns.

### CODE REVIEW

**Comment by jfbastien** [comment]
Great! Do you also have polls in mind? Or is it just an update, and you want implementation experience before going forward?

**Comment by sunfishcode** [comment]
The main next step for this feature seems to be to [enter Phase 3](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#3-implementation-phase-community--working-group), as it seems to meet the stated requirements. Since the process is new, I imagine the CG may wish to discuss how to manage this process at the meeting. However, I'm open to input as to how to proceed here.

**Comment by jfbastien** [comment]
Right, I think you probably just want to poll for entrance to phase 3.

**Comment by sunfishcode** [comment]
Created https://github.com/WebAssembly/meetings/pull/78 to add such a poll.

**Pull request merged**
