### PR TITLE
Add discussion of identity in wasm vs JS

### PR DESCRIPTION
**Pull request by RossTate**

### CODE REVIEW

**Comment by binji** [comment]
Would you mind providing a time estimate for this discussion (as mentioned in #595)? I'd like to try it out for this meeting.

**Comment by RossTate** [comment]
I'm guessing 15-20. Should I put a range in and then when the meeting comes up and the items are more settled you can decide where in that range the box should be?

**Comment by binji** [comment]
Yep, that sounds good to me. @tlively added a little `[15 minutes]` after his agenda items, can you do the same here?

**Comment by RossTate** [comment]
Done

**Pull request merged**
